name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  doc_build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build Templates Page
        run: |
          python ./doc/source/generate_templates_docs.py

      - name: Build Documentation
        run: |
          pip install -r requirements.txt
          pip install -r requirements_doc.txt
          cd doc/
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          BRANCH: gh-pages
          FOLDER: doc/build/html
          CLEAN: true
